---
title: "Домашна работа 2  по R"
author: "Николай Желязков, 82022"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## **Задача 1**

```{r}
  #Проверяваме дали отхвърля H0
denyZeroHyp = function(n){
  t = table(sample(1:6,size = n,replace = T))
  result = chisq.test(t)$p.value<0.05
  result
}
```

```{r}
#Гледаме какъв процент от всички отхъврлят H0
f1 = function(n){
  s = sum(replicate(10000,denyZeroHyp(n)))/10000*100
  result = paste(s, "%")
  result
}
f1(100)
f1(200)
f1(400)
```

## **Задача 2**

```{r}
#Проверяваме дали данните са от нормално разпределение
checkNormality = function(n) {
    x = runif(n, 5, 12)
    hypResults = shapiro.test(x)$p.value > 0.05
    hypResults
}
```

```{r}
#Намираме  Колко често заключението на теста е вярно 
f2 = function(nBig,n){
  results = replicate(n=nBig,checkNormality(n))
  prop.table(table(results))
}
f2(10000,15)
f2(10000,25)
f2(10000,50)
f2(10000,90)
```

## **Задача 3**

```{r}
#Функция четаеща графиката на оценката на бета1
graphics = function(beta1_est){
  hist(beta1_est)
  qqnorm(beta1_est)
}
```

```{r}
f3 = function(n){
  beta1 = 5
  # 4 реда - по 1 за всяка подточка
  beta1_est =  matrix(data = NA, nrow = 4, ncol = 10000)
  beta1_sd_err = matrix(data = NA, nrow = 4, ncol = 10000)
  beta1_sd_err = matrix(data = NA, nrow = 4, ncol = 10000)
  leftConfInt = matrix(data = NA, nrow = 4, ncol = 10000)
  rightConfInt = matrix(data = NA, nrow = 4, ncol = 10000)
  
  #генерираме данните 10000 пъти
  for (k in 1:10000) {
    x = sample(1:10, size = n, replace = TRUE)
    
    # а)
    e = rnorm(n, mean = 0, sd = 2)
    y = beta1 * x + e
    
    df = data.frame(x, y)
    model = lm(y ~ x, data = df)
    model_summary = summary(model)
   
    beta1_est[1, k] = model_summary$coefficients[2, 1] # оценка на бета1
    beta1_sd_err[1, k] = model_summary$coefficients[2, 2]
    leftConfInt[1,k] = confint(model)[2,1] #левия край на дов. интервал за бета1
    rightConfInt[1,k] = confint(model)[2,2] #десния край на дов. интервал за бета1
    
    # б)
    e = runif(n, -3.5, 3.5)
    y = beta1 * x + e
    
    df = data.frame(x, y)
    model = lm(y ~ x, data = df)
    model_summary = summary(model)
    p = paste("b)")
    beta1_est[2, k] = model_summary$coefficients[2, 1] # оценка на бета1
    beta1_sd_err[2, k] = model_summary$coefficients[2, 2]
    leftConfInt[2,k] = confint(model)[2,1] #левия край на дов. интервал за бета1
    rightConfInt[2,k] = confint(model)[2,2] #десния край на дов. интервал за бета1
    
    # в)
    v = rexp(n, 0.7)
    w = rexp(n, 0.7)
    e = v - w
    y = beta1 * x + e
    
    df = data.frame(x, y)
    model = lm(y ~ x, data = df)
    model_summary = summary(model)
    beta1_est[3, k] = model_summary$coefficients[2, 1] # оценка на бета1
    beta1_sd_err[3, k] = model_summary$coefficients[2, 2]
    leftConfInt[3,k] = confint(model)[2,1] #левия край на дов. интервал за бета1
    rightConfInt[3,k] = confint(model)[2,2]  #десния край на дов. интервал за бета1
    
    # г)
    u = rexp(n, 0.5)
    e = u - 2
    y = beta1 * x + e
    
    df = data.frame(x, y)
    model = lm(y ~ x, data = df)
    model_summary = summary(model)
 
    beta1_est[4, k] = model_summary$coefficients[2, 1] # оценка на бета1
    beta1_sd_err[4, k] = model_summary$coefficients[2, 2] 
    leftConfInt[4,k] = confint(model)[2,1] #левия край на дов. интервал за бета1
    rightConfInt[4,k] = confint(model)[2,2]  #десния край на дов. интервал за бета1
  }
   #Създаваме матрица за крайните резултати
  tbl = matrix(data = NA, nrow = 4, ncol = 3)
  rownames(tbl) = c("а)", "б)","в)","г)")
  colnames(tbl) = c("Колко често доверителният интервал за бета1 съдържа истинската стойност?",
                    "средната дължина на доверителния интервал на базата на 10000 повторения",
                    "средното на beta1_est на базата на 10000 повторения")
  for (k in 1:4) {
    tbl[k, 1] = paste(sum((beta1 > leftConfInt[k,]) & (beta1< rightConfInt[k,])) / 10000 * 100, "%") 
    tbl[k, 2] = mean(rightConfInt[k,] - leftConfInt[k,]) # (-beta1_sd_err , +beta1_sd_err)
    tbl[k, 3] = mean(beta1_est[k,]) 
  }
  n = paste("N =",n)
  print(n)
  #Чертаем графиките 
  graphics(beta1_est)
  print(tbl)
  
}
```

```{r}
#Пускаме резултатите за различни стойности на n
ns = c(30, 50, 100, 500)
for (n in ns) {
  f3(n)
}
```
